version: '2.1'
orbs:
  browser-tools: circleci/browser-tools@1.2.4
      
jobs:
  test:
    docker:
      - image: 'cimg/node:13.12-browsers'
    steps:
      - browser-tools/install-browser-tools
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            git pull
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb || true; sudo apt-get -fy install
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt --upgrade
            python main.py --update --force
            git config --global user.email "chrigi@hotmail.com"
            git config --global user.name "Christian Baumann"
            git add .
            git commit -m "[skip ci]"
            git push
          name: Test

workflows:
  main:
    triggers:
      - schedule:
          cron: "19 9,18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-test
