version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            echo "Test"
            touch test.txt
            git add .
            git commit -m "[skip ci]"
            git push
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
