version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: |
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python main.py --update
            rm test.txt
            git config --global user.email "chrigi@hotmail.com"
            git config --global user.name "Christian Baumann"
            git add .
            git commit -m "[skip ci]"
            git push
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
