version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run:
          command: |
            git pull
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt --upgrade
            python main.py --update --force
            git config --global user.email "chrigi@hotmail.com"
            git config --global user.name "Christian Baumann"
            git add .
            git commit -m "[skip ci]"
            git push
          name: Test

workflows:
  main:
    triggers:
      - schedule:
          cron: "19 9,18 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-test
